# Generated by Django 4.2.13 on 2024-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='profile_pictures/blank-profil.webp', upload_to='media/profile_pictures/'),
        ),
    ]
