# Generated by Django 4.2.13 on 2024-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_profilepicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(upload_to='media/profile_pictures/'),
        ),
    ]
