# Generated by Django 4.2.13 on 2024-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_userimage_user_profile_album_userimage_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='album_pictures/default.png', upload_to='album_pictures/'),
        ),
    ]
