# Generated by Django 4.2.13 on 2024-06-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoticon',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='emoticon',
            name='related_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='emoticon',
            name='related_profile_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.profilepicture'),
        ),
        migrations.AlterField(
            model_name='emoticon',
            name='related_user_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.userimage'),
        ),
    ]
