# Generated by Django 4.2.13 on 2024-06-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_userprofile_comments_alter_userprofile_posts_and_more'),
        ('posts', '0007_alter_emoticon_post_alter_emoticon_related_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoticon',
            name='related_user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='Profiles.userprofile'),
            preserve_default=False,
        ),
    ]
