# Generated by Django 4.2.13 on 2024-06-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_userprofile_comments_alter_userprofile_posts_and_more'),
        ('posts', '0011_alter_emoticon_post_alter_emoticon_related_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emoticon',
            unique_together={('related_user_img', 'related_user')},
        ),
    ]
