# Generated by Django 4.2.13 on 2024-06-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_emoticon_unique_together_alter_emoticon_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pictures',
        ),
        migrations.AddField(
            model_name='comment',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.userimage'),
        ),
    ]
