# Generated by Django 4.2.13 on 2024-05-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='emoticon',
            name='post',
        ),
        migrations.RemoveField(
            model_name='emoticon',
            name='related_comment',
        ),
        migrations.RemoveField(
            model_name='emoticon',
            name='related_profile_img',
        ),
        migrations.RemoveField(
            model_name='emoticon',
            name='related_user_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user_profile',
        ),
    ]
