# Generated by Django 4.2.13 on 2024-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_remove_comment_pictures_remove_comment_post_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Emoticon',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
